### ISSUE TITLE
Docker images model

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#19]
* create model for managing available docker images for jobs
* the `ufdl-core-app/src/ufdl/core_app/migrations/docker_images` directory contains CSV file with currently available images
* create migration to load CSV into database
* [API details](https://waikato-ufdl.github.io/ufdl-api/docker_images/)
* restricted to admin users

**Comment by fracpete** [comment]
Added *cpu* column to CSV file. Please add a cpu bool flag to the model.

**Comment by csterling** [comment]
This is implemented as of commit 73f74175fda1ae543c380f37c57717c70cdb872f
