### ISSUE TITLE
Commit #6552bd3 breaks installation

### ISSUE THREAD

**Issue by michaeliwaikato** [waikato-ufdl/ufdl-backend#29]
[This change](https://github.com/waikato-ufdl/ufdl-backend/commit/6552bd39f03f5ef0d6e92e9735ca0b7be39cfdc6) causes the installation of the backend to fail.

**Comment by fracpete** [comment]
Fixed with https://github.com/waikato-ufdl/ufdl-backend/commit/16e06eac197f3fdac2050360c71c734c1bfd3b4d
