### ISSUE TITLE
Double-copying datasets

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/ufdl-backend#30]
Current functionality is that copying a dataset without providing a new name results in a version bump.

If the same version of the same dataset is copied more than once, this will attempt to create another dataset with the same name and version, violating the unique datasets constraint.

**Comment by csterling** [comment]
Couple of options:
1. Make copying a dataset assign the next available version number to the copy, instead of current++. This will technically solve the problem, but the notion of version number ordering will be lost.
2. Create a tree structure i.e. each dataset stores a `parent` field which points to another dataset (or `null` in the case of new datasets).

**Comment by fracpete** [comment]
Go with option 1. Maybe also storing what the previous version was?

**Comment by csterling** [comment]
This functionality has been implemented in commit 1bf854bd1ec3e253968571aaa28ccedbe3b90cdc
