### ISSUE TITLE
CPU-based docker images don't have "min_hardware"

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#31]
* remove restriction of docker images requiring a `min_hardware` field when `cpu=true` (`docker_images.csv`)
* currently `tf_imageclass_cpu` has `Fermi` as `min_hardware`, remove once above restriction no longer necessary

**Comment by csterling** [comment]
Implemented in commit 06ca9b709e6c1e9b1fada4236df7ab7904a85ea4
