### ISSUE TITLE
Docker image model uses string for CUDA version

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#36]
* currently the Docker image model uses a string for the CUDA version
* switch to the CUDA version model instead

**Comment by csterling** [comment]
I think this is already the case? The serialiser automatically translates between the string `full_version` field on the `CUDAVersion` model and its `pk`, is this what you're referring to?

**Comment by fracpete** [comment]
This is different to most, if not all, other models (eg teams, projects, frameworks) that use the PK instead of a string. If the CUDA version gets updated (eg the full version changes), then it will point to nothing. Using the PK would prevent that. The CSV import when bootstrapping the database should resolve the version into the PK.

**Comment by csterling** [comment]
It's only during serialisation that the `full_version` string is used. The `DockerImage` table in the database does store the `pk` internally. So when you do a `retrieve`/`list` request, you see the `full_version` string in the (serialised) JSON response, and when you do a `create`/`update`, you supply the same string, but the serialiser always resolves it to the (unique) corresponding row from the table.

This technique is used for a couple of other models, but is only possible when there is a one-to-one relationship between the `pk` and the related field. Hence why the `full_version` field is used and not the `version` field (there are multiple CUDA versions where `version` is 8.0, so a unique mapping to `pk` can't be created).

**Comment by fracpete** [comment]
Ah, didn't see the duplicate 8.0. However, the docker base images don't use the full version in their names, only the short one. I removed the duplicate 8.0 entry and left only the newer one (8.0 is only of historic interest nowadays). Please switch to using the short version. The full version is only stored as additional information but won't get used.

**Comment by fracpete** [comment]
Ah, didn't see the duplicate 8.0. However, the docker base images don't use the full version in their names, only the short one. I removed the duplicate 8.0 entry and left only the newer one (8.0 is only of historic interest nowadays). Please switch to using the short version. The full version is only stored as additional information but won't get used.
And we'll assume a 1-to-1 relationship between short/full version.

**Comment by csterling** [comment]
Yes, the migration that adds the initial set of Docker images translated the short version (unchecked!). I'll switch it to use the short version for serialisation and to check for a unique match in the migration.

Are you happy with the serialisation equivalence on the whole though? It really just means that when you retrieve the value or supply it, you're getting/sending a (hopefully) meaningful (to a human) string, rather than an integer.

**Comment by fracpete** [comment]
We'll just stick with using a string for the time being and re-evaluated post September. Personally, I'd like to be consistent across the API in terms of whether IDs or strings are being used. It gets a bit confusing if there is a mix.

**Comment by csterling** [comment]
> I'll switch it to use the short version for serialisation and to check for a unique match in the migration.

These changes are implemented in commit ace096682b0579f162c7079e9de0ef17b5b24b77
