### ISSUE TITLE
Docker images: domain and task

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#38]
* the domain in the CSV file should get enforced against the `domain` model (I've updated the CSV file accordingly)
* the `task` column in the CSV file is now a comma-separated list of `job types` and should be treated as a list by the API

**Comment by csterling** [comment]
> * the domain in the CSV file should get enforced against the `domain` model (I've updated the CSV file accordingly)

Implemented in commits d967f201728adef9c16e96a06ddf3db4b8159146 & c542b0e87e51a93041f16d8690a7dd6634dfa8d9

> * the `task` column in the CSV file is now a comma-separated list of `job types` and should be treated as a list by the API

Implemented in commit 0c088b4849e989e998362ee44f0bb8e8d2ef3c32
