### ISSUE TITLE
Convert string representations to PKs

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/ufdl-backend#40]
While string representations are nice from a human-readability point-of-view, having them in JSON output means an extra API call is required to convert them to PKs for other functionality.

Remove all slug serialisation equivalences.

**Comment by csterling** [comment]
Here's a full run-down of the fields that would now be PKs (current type in brackets):

- **Jobs**
  - source template (name and version string)
  - docker image (name and version string)
  - outputs (signature string)
- **Job Templates**
  - data-domain (2-letter code string)
  - job type (name string)
  - inputs (signature string)
  - parameters (signature string)
- **Models**
  - data-domain (2-letter code string)
  - licence (name string)
- **Docker Images**
  - CUDA version (version string)
  - minimum hardware generation (name string)
  - data-domain (2-letter code string)
  - applicable job-types (name string)
- **Nodes**
  - hardware generation (name string)
- **Datasets**
  - files (filename string)
- **Licences**
  - permissions, conditions, limitations, domains (all name strings)
- **Teams**
  - members (username strings)

My recommendation for would be to leave the following as-is:

- Job outputs (end-points for operating with job outputs work exclusively with names, not PKs)
- all data-domain/job-type fields (are a simple unique string, as opposed to a formatted string combining multiple fields)
- Job template inputs/parameters (although could be converted to a JSON object with separate fields for name and type, rather than a formatted string)
- Dataset files (end-points for operating with files work exclusively with filenames, not PKs)
- All licence fields (simple unique string)

**Comment by fracpete** [comment]
Sounds good!

**Comment by fracpete** [comment]
And job-template inputs/parameters should be a separate JSON structure as well, as it needs to be read in the user interface (and I don't want to write a separate parser for that). Just like job inputs/parameter values should be a JSON structure as well.

**Comment by csterling** [comment]
This is implemented in commit c9cf500a173d53ecbc4f0438d1f44a60fb7ffb64.

Final set of changes:
- **Jobs**
  - `template` field is serialised to an object: `{"pk": 1, "name": "my_template", "version": 1}`
  - `docker_image` field is serialised to an object: `{"pk": 1, "name": "tf_imageclass", "version": "1.14"}`
  - `outputs` field is serialised to an array of objects: `[{"name": "Output1", "type": "str"}, {"name": "Output2", "type": "int"}]`
- **JobTemplates**
  - `inputs`/`parameters` fields are serialised to an array of objects: `[{"name": "Input1", "type": "str"}, {"name": "Input2", "type": "int"}]`
- **Models/Pre-Trained Models**
  - `licence` field is serialised to/specified by PK instead of name
- **Docker Images**
  - `cuda_version`/`min_hardware_generation` fields are serialised to/specified by PK instead of version/generation name respectively
- **Nodes**
  - `hardware_generation` field is serialised to/specified by PK instead of generation name
- **Teams**
  - `members` field is serialised to an array of objects: `[{"pk": 1, "username": "User1"}, {"pk": 2, "username": "User2"}]`
