### ISSUE TITLE
Job template: input/parameter only retrieve name/type from DB?

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#42]
* adding a job template to the backend stores `options` for `input` and `default` for `parameter`
* when loading a job template from the backend, `options` and `parameter` are empty
* the serializers for input/parameter in `ufdl/core_app/serialisers/jobs/_JobTemplateSerialiser.py` only list name/type - is that the issue?

**Comment by csterling** [comment]
Yes that is the issue. I'll fix it now.

**Comment by csterling** [comment]
Implemented in commit 1c735879047983f84083c451fe8f563232007575
