### ISSUE TITLE
Pretrained model add "name" to table

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#43]
* add field `name` to pretrained model (kind of nickname for model)
* add migrations for pretrained models for each of the domains, using a CSV file (I will fill in some pretrained models)

**Comment by csterling** [comment]
@fracpete How do you want to specify the `data` field for the model (contains the model's file data)?

**Comment by csterling** [comment]
> @fracpete How do you want to specify the `data` field for the model (contains the model's file data)?

Is this the purpose of #44?

**Comment by fracpete** [comment]
The files for the pretrained models should use the same backend as the datasets, so you never store the model data itself in the database (some of the models are several 100MB). And yes, the facade (#44) would allow us to defne a large model zoo, without taking up any disk space (only the ones you actually use will get downloaded).

**Comment by csterling** [comment]
> * add field `name` to pretrained model (kind of nickname for model)

This is implemented in commit be3eeee4dfe60649812f19c9501eed518fab493e

> * add migrations for pretrained models for each of the domains, using a CSV file (I will fill in some pretrained models)

This is implemented in commit fc3b755f864974874e21314cc97e143a5a533027
