### ISSUE TITLE
Facade for pretrained models

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#44]
In order to avoid initial population of pretrained models backend with GBs of pretrained models, use lazy approach:
* add API endpoint for downloading a pretrained model via PK
* **if** pretrained model is not yet present when queried, use URL to download it and return it; **else** return pretrained model

**Comment by csterling** [comment]
This is implemented in commit ed67938cd0a6644e3070e932d83286cbc9ae610f
