### ISSUE TITLE
Add license to docker images and job templates

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#45]
* extend models for `docker_image` and `job_template` to include a license field
* `docker_images.csv` files have been extended already (using the name of the license)
* methods `iterate_docker_images` and `add_initial_docker_images` in `_docker.py` have been adapted to work with the extended CSV files

**Comment by csterling** [comment]
Implemented in commit c7effb455d44c1c03754fc1e94e71af51c05971a

**Comment by fracpete** [comment]
The python client still seems to be missing the license parameter for docker images and job templates.

**Comment by csterling** [comment]
Sorry forgot to push. Done now
