### ISSUE TITLE
Prepare for job template migrations

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#46]
* add ability to easily add migrations for job templates (per domain)
* job template migrations are stored in json format to make editing easy, resembling create request for job templates
* any field that requires resolution (e.g., framework/license) will be supplied as text instead of PK, to make it easier for the maintainer; strings that contain multiple fields, like framework, separate the individual parts with `|`

**Comment by csterling** [comment]
Implemented in commit 0fb84aa4f664b777f82cabda834f817b3f5d6f58 and in [this commit](https://github.com/waikato-ufdl/ufdl-json-messages/commit/02f87e423b4052af0b4786f82ef05b558ced0507) in the JSON messages repo.

**Comment by fracpete** [comment]
* add ability to specify a help string for inputs/parameters, to be used in the user interface
* instead of using `|` compound fields for inputs/parameters use proper JSON notation instead (making it easier to reuse job templates obtained from the backend in the migration); per input/parameter:
  * name
  * type
  * options (input) / default (parameter)
  * help (optional)

**Comment by csterling** [comment]
Implemented in:
- 505c4fec432b7638351507cb5c1b5f28a24675fd
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/d8e646ce5d43e812b85d05def01423aaed75eeb6)
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/5ae86d293eea0be0e271ac83e700dbbb4721c8bf)
