### ISSUE TITLE
filter: is_null

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#48]
in order to list jobs that haven't been started yet (`start_time` is null), an additional filter for listing rows with nulls in a field is necessary, e.g., called `is_null`

**Comment by csterling** [comment]
Implemented in:
- 5a9a7450d2bee4bcdc0f172a281f717c5feaf7f1
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/0f17fe6ea73369e21422ca9aeec9777439990daa)
