### ISSUE TITLE
filters: gt, ge, lt, le

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#50]
More filters:
* gt - greater than
* ge - greater or equal
* lt - less than
* le - less or equal

**Comment by csterling** [comment]
Implemented in:
- 0d0c396d775833850aafcd0d9a4085eff77f7b37
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/80707dc26e87d687af1f4a856e965902202e1e73)
