### ISSUE TITLE
Merge a dataset into another one

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#51]
In order to make predictions (e.g., classifying images with a built model), the user will create a new dataset (with the unlabeled images) and then kick off a prediction job (supplying the job number with the model). The prediction job will then use the model to make predictions (predicting labels for the images) and these get stored back in the dataset via the backend API. This approach allows reusing existing functionality for viewing, updating, etc. However, in order to be able to make use of these new predictions, to enhance an existing dataset, the user needs to be able to merge one dataset into another one (optionally deleting the one that got merged into the base one).

**Comment by csterling** [comment]
This may require a little more explanation. Two things I can think of off the bat:
1. A merge-with-delete is conceptually 3 operations: a read of the source data-set, a write of the target data-set, and a delete of the source data-set. This makes the permissions a bit tricky as the user performing the merge might have different permissions to the two data-sets.
2. How to handle the over-writing of existing information in the target data-set (e.g. if a file already exists, or already has annotations)?

**Comment by fracpete** [comment]
1. Check if user has `W` access to source and target datasets, if not the API call will fail with an appropriate error message. That allows the user to copy the source dataset (if only `R` access) to get `W` access and try again.
2. The merge should disambiguate files if their hash is different by adding a suffix (in between name and extension, e.g., `-NNNN`); if the hash is the same then overwrite any existing annotations.

**Comment by csterling** [comment]
Implemented in:
- b86335cf8db4bbf88c58c3e59d929ef29330df42
- [ufdl-json-messages](254be7e080cffee1b56a5f2ba31b1e4e412ff1b0)
- [ufdl-python-client](23e9a51a84938727a8da8b1f73a94f7b316ff676)

**Comment by csterling** [comment]
Add the ability to specify if the delete is soft or hard.

**Comment by csterling** [comment]
Implemented in:
- 2826110f16f588994ca8667866c4860a9aa14e0a
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/87bdeece651e3dc129bb25c9a8845f5d26a69043)
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/bafea7689f4377098c4f8e1c1501571da3491627)

**Comment by csterling** [comment]
The body to the merge end-point should now be:

```json
{
  "delete": true,
  "hard": true
}
```

for a hard delete. The `hard` field is optional and defaults to `false` if omitted.
