### ISSUE TITLE
End points for starting/finishing a job

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#52]
Job executors need to mark when they started a job and when they finished one. This could be achieved by simply setting the `start_time` and `end_time` fields in the job table. But this does not cover sending out notifications, e.g., email, SMS or push notifications).

Instead, create new API endpoints which the job executors can call:
* `job-started` (POST, with job PK in URL)
  * parameters: send_notification (str, e.g. "email" or "" for no notification)
* `job-finished` (POST, with job PK in URL)
  * parameters: success (true|false), send_notification (str, e.g. "email" or "" for no notification)
The `send_notification` flag indications whether to send out notifications. Not every job should send out notifications, e.g., a meta-job could turn off notifications for all its sub-jobs and only informs the user when the overall job has started/finished.

In order to send out notifications, a template table must be available:
* status: started, finished_success, finished_failed
* type: email
* class: the Python class for sending out the notification
* body: JSON (the sender class interprets this content)
When the `job-finished` end point gets called, it determines based on the type of notification (and success) what class needs to be executed with what body.

**Open question:** how to make configuration, e.g., for email (SMTP host/port, TLS, login details) available to notification class.

**Sending out notifications** functionality can be pushed past September. Having the API endpoints for marking jobs as started/finished has priority.

**Comment by csterling** [comment]
I have added the end-points for starting/finishing jobs:
- 1b030e875fbe05838d81d637c1610bcb991eda02
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/6bba7af7dc779f070b483797b2884520991389bf)
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/3b5d4c530e7675b1828530f1bb7a19b3928dbef6)

To start a job, POST to `../v1/core/jobs/JOB_PK/start` with the following JSON:

```
{
  "send_notification": "email"
}
```

To finish a job, POST to `../v1/core/jobs/JOB_PK/finish` with the following JSON:

```
{
  "success": true/false,
  "send_notification": "email",
  "error": "my error message"
}
```

Currently the `success`/`send_notification` fields are ignored, but in place for future use. The error message is optional.

I have added permissions/errors to control the job lifecycle. A node-user should make calls in the following order:

```
acquire -> start -> [add_output]* -> finish
```

**Comment by fracpete** [comment]
Looks perfect!
