### ISSUE TITLE
Add description field to job

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#54]
For allowing humans to better distinguish between jobs (and search through them), add an optional `description` text field to the `job` model.

**Comment by csterling** [comment]
In light of #55, when a job is created from a template, should the job inherit the description of the template, or are these two descriptions distinct?

**Comment by fracpete** [comment]
No, that description is for the user to put in notes about that particular job. The template description is more of a general description about what it can do.

**Comment by csterling** [comment]
Implemented in:
- 583fcbeff6a681131cfa6f1414c467ad3413ff44
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/b6b99868c20bcf575f6e0175b6e9f0a53e312f8b)
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/06fad87ff9e5624efd5d49184b7c8c0377e67872)
