### ISSUE TITLE
Download of datasets: parameters in body of GET request rather than as part of URL

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#56]
Rather than constructing a long URL with the file type and wai.annotations options, pass `filetype` and `annotations_args` in the body as json as part of the GET request.

**Comment by csterling** [comment]
This is implemented in:
- 1a561f0ac4ca2f65cfc765b91432fc0503d11a66
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/d1b70c46a4b5fcb846b44e08e9e1a238f3e43f08)

The `download` end-point expects a JSON body in the following format:

```json
{
  "filetype": STRING,
  "params": QUERY-PARAMS
}
```

`QUERY-PARAMS` is an object where each entry is either a string or an array of strings, e.g.:

```json
{
  "filetype": "zip",
  "params" : {
    "param1": "just a string",
    "param2": ["an", "array", "of", "strings"],
    ...
  }
}
```

For datasets the only expected `param` is `annotation_args`, so the expected body as a whole is, for example:

```json
{
  "filetype": "tar.gz",
  "params": {
    "annotation_args": ["to-coco", "--pretty"]
  }
}
```
