### ISSUE TITLE
Data domain: add longer description

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#57]
To make selecting a data domain in the user interface *more user-friendly*, a longer description for the domains would be helpful:
* ic - Image classification
* od - Object detection
* sp - Speech

**Comment by csterling** [comment]
I've implemented this in cc83b44bcef0337e31fcec762049668eb10802f7. It'll show up in the database (auto-populated by the domain-specific apps) and when you do a list/retrieve of data-domains. Is there anywhere else you want this to show up?

**Comment by fracpete** [comment]
No, list/retrieve is fine. The short name is fine for internal use.
