### ISSUE TITLE
No GET bodies

### ISSUE THREAD

**Issue by csterling** [waikato-ufdl/ufdl-backend#62]
Modify views to never use GET requests with bodies.

**Comment by csterling** [comment]
Actions that currently use `GET` method with a body:
- `download`: body specifies the archive type and the `wai.annotations` arguments.
- `list`: body specifies filtering of results.

I will change both of these to use `POST` instead, but as `POST` is already reserved for the `create` action on the non-detail URL for models, I will put this action on a new URL, `../MODEL/list`.

**Comment by fracpete** [comment]
To be consistent, it would be good to use `/create`, `/list` and `/download` as URLs. Then it's easy to tell from the URL what action is being carried out.

**Comment by csterling** [comment]
Implemented in:
- d423822d4f2a5af2a43938e1bce3140646cf4369
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/fc6fc412c939a79af1b90c23b4463095e7faee2a)
