### ISSUE TITLE
Import/export of job templates

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#68]
Rather than manually setting up a job-template via multiple API calls (add/add input(s)/add parameter(s)), allow admins to quickly import/export templates in the same JSON format as the initial database setup already uses via these endpoints:
* POST: `/v1/job-templates/import`
* GET: `/v1/job-templates/export`
Can override existing job templates, hence only for admins.

**Comment by csterling** [comment]
Implemented in:
- afbb2ab4dfa4aefd2ae8abdace28aef8ecb65d86
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/e99bfd36ee989f1045491993462b0140f0a70603)
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/a074556361e505e5169264db257a183d0b49029d)

URL for export is `/v1/job-templates/PK/export`.
