### ISSUE TITLE
Get meta-data for dataset, not just file

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#69]
In order to speed up retrieval of meta-data (e.g., confidence scores) and retrieve the number of API calls, an API end point to retrieve all meta-data associated with a dataset should be available. The existing end point for retrieving the meta-data for a file of a dataset could be repurposed for that: by leaving out the file name, all of the meta-data is returned (with the additional layer of file names, of course).
[Current end point](https://waikato-ufdl.github.io/ufdl-api/datasets/#get-meta-data):
`GET: /v1/datasets/{PK}/metadata/{NAME}`
Should become:
`GET: /v1/datasets/{PK}/metadata[/{NAME}]`

**Comment by csterling** [comment]
Implemented in:
- f0c1d44544cff19148d9de61968b718b193b5a0a
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/d50d531c2f18b7eb501cc641b1dd19bec022dc1b)

The JSON returned by the bulk end-point is:

```json
{
  "filename1": "meta-data for file 1",
  "filename2": "meta-data for file 2",
  ...
}
```
