### ISSUE TITLE
Add support for job pipelines

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#70]
In order to automate tasks, like building an Android once a model has been built, the backend needs to support job pipelines.

# API changes
Additional fields:
* job template: `is_pipeline: true|false` (default is `false`)
* job template inputs add `forward: true|false` flag, indicating whether this parameter should be made available to subsequent jobs
* job: `pipeline: str` (None, or JSON array with remainder of pipeline)

# Defining a pipeline
The pipeline gets defined in the `body` of the job template, using the `[parent,[children*]]`format.
`parent` and `children` job templates are referenced using their `name` and `version`, i.e., `name|version`.
```
[A|1,[B|7,[C|3]]]
```
Branching is possible as well (`B/D/E` are children of `A`, `C` is child of `B`):
```
[A|1,[[B|7,[C|3]]],[D|1],[E|2]]
```

# Executing a pipeline
The user interface determines with the `is_pipeline` flag in the template whether it needs to read body for determining the first actual job template (and determine the required inputs/parameters). This job, when submitted, will have the remainder of the pipeline in the `pipeline` field.
Once a job gets marked as finished by the job launcher, the backend then checks whether the `pipeline` field is empty or not. If non-empty, it will create subsequent job(s), using the outputs of the job (and potential forwarded inputs) as the new inputs for the job.

# Notifications
Notifications are only sent when a job either fails or has no subsequent jobs left to execute (i.e., is a leaf), instead of sending out a notification with every job finishing.

**Comment by csterling** [comment]
Implemented in:
- dd52a9365ea773db1983c8bd47ad7ac2c7432f2c
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/8cee0edfca7e456915ef3837e4a9da44c3d743c8)
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/d9e2dbe842c971f4292dbd803a5081378a603eec)

A pipeline is defined as follows:
```json
{
  "name": "my_pipeline",
  "version": 1,
  "description": "Example of a pipeline job-template definition.",
  "scope": "public",
  "domain": "ic",
  "licence": "Apache 2.0",
  "specific": {
    "nodes": {
      "sub_template_1": {
        "name": "my_other_template_1",
        "version": 1,
        "parameter_default_overrides": {
          "parameter_1": "new_parameter_default_value",
          "parameter_2": "other_new_parameter_default_value"
        }
      },
      "sub_template_2": {
        "name": "my_other_template_2",
        "version": 1
      }
    },
    "dependencies": [
      {
        "from_node": "sub_template_1",
        "from_output": {
          "value": "output_1",
          "type": "my_type"
        },
        "to_node": "sub_template_2",
        "to_input": "input_1"
      }
    ]
  }
}
```
