### ISSUE TITLE
Re-run job

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#71]
If a job fails due to a job template containing an error, if would be useful being able to re-run the failed job again (after the issue has been fixed). Re-running the job would remove error, start/end times and also any outputs.

**Comment by csterling** [comment]
Implemented in:
- 18f5f9957da3ca70ebed8574fb1b8e995107cc23
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/b355573d3f0b66e89303b82aeda0f04cd860f8c0)

**Comment by csterling** [comment]
I have added couple of extra methods for controlling the life-cycle of a job, release and abort.

The current life-cycle of a job is:

```
Normal life-cycle, completes successfully, all methods performed by the same node:
[created] --acquire-> [acquired] --start-> [started] --finish-> [finished]

Completes with error, performed by the node that owns the job :
[started] --finish-> [finished with error]

Reset, can be performed by the node itself or an admin:
[finished with error] --reset-> [acquired]

Node voluntarily releases job:
[acquired] --release-> [created]

Abort (can be performed by an admin only, resets and releases the job)
[created|acquired|started|finished with error] --abort-> [created]
```

**Comment by fracpete** [comment]
The `abort` action sounds really useful for an admin, already added that to the flow managing the backend.
The `abort_job` action in the python-client was calling the `reset_job` mixin, which I fixed.
