### ISSUE TITLE
Clean up datasets

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#72]
When pre-labeling a dataset, I can quite easily happen that you do that with a dud model.
In order to quickly clean up a dataset, the following dataset-wide operations would be helpful:
* remove meta-data (or simply set it to empty string; all domains)
* remove categories (image classification)
* remove annotations (object detection)
* remove transcripts (speech)

At the moment, I have to manually go through an image classifcation dataset and unset the category for each image.

**Comment by csterling** [comment]
Implemented in:
- 63050a0da5054531997f9757ce1ef3a4c7f6b0b1
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/52593f518c22946388034f1b94707fb02bd0cf38)

**Comment by fracpete** [comment]
The `jobexec` user received a `Forbidden: /v1/classify/datasets/2/clear` when trying to clear the dataset before generating predictions. Should be same permissions as storing predictions back in dataset.

**Comment by csterling** [comment]
Implemented in 426deddb5f12340fc9ee68bbedc691463320effa
