### ISSUE TITLE
Pre-trained models cannot be downloaded unless admin?

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#77]
Currently, job executor users (permission X) cannot download pretrained models for running build jobs. It looks like the user has to be an admin in order to download a pre-trained model:

```
Forbidden: /v1/pretrained-models/5/download
[30/Sep/2020 11:37:58] "POST /v1/pretrained-models/5/download HTTP/1.1" 403 63
```

Downloading pre-trained models should be available to anyone.

**Comment by csterling** [comment]
Implemented in:
- de2373c44b27d0313916ec51984f64d9023eab95
