### ISSUE TITLE
Deleting an image does not remove it from categories?

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#79]
The Image classification app team uses the *get categories* (`/v1/classify/{PK}/categories`) API call to determine what files are in the dataset. However, when deleting an image, this image does not seem to disappear from the *get categories* list, only its categories get emptied.

**Comment by csterling** [comment]
@fracpete I have tested this with a small example case, and as far as I can tell it is working as expected.

My setup:
1. Create a new team/project/dataset.
2. Add 2 unique images to the dataset, and give them each a unique category.
3. Perform call to `get_categories`, confirm categories are as specified in step 2.
4. Delete one of the images from the dataset.
5. Perform second call to `get_categories`, see that deleted image is no longer returned in result.

Without more information I don't know what else to do...

**Comment by fracpete** [comment]
Inconsistent state derived from calling the delete_file method using the core dataset API endpoints.

**Comment by csterling** [comment]
Was this in an older version of the code-base? Since e8c530d1b86e9a400999d29125f795f6474189fb using the `core` end-point is equivalent to using the domain-specific end-point for the data-set in question.

**Comment by fracpete** [comment]
Quite possibly.
