### ISSUE TITLE
Allow meta-data for pre-trained models 

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#82]
* add an unstructured field for storing meta-data alongside a pre-trained model
* meta-data field can contain information about labels that a model was trained with (allowing the immediate application of a pre-trained model for labeling images)

**Comment by csterling** [comment]
Implemented in:
- c0ae243dcd7fbcd69e6671d6a6b5c212685f4377
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/e22f80743e939433132ad9673d71a15d6596750a)
