### ISSUE TITLE
"Ping" endpoint for nodes for "last_seen" update

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#88]
Provide a simple API endpoint for nodes to let the backend know that they are still alive, updating the `last_seen` timestamp.
```
/v1/nodes/ping
```

**Comment by csterling** [comment]
Implemented in:

- 7d8af3a0353d65633784fa5cc065e1601b4a374c
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/36a905aecf26ac04088c9c05af75631bb9fc0046)

Access via GET request to `v1/nodes/ping`.
