### ISSUE TITLE
Push dataset generation into client node

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#89]
Currently, the worker nodes request datasets in the correct format from the backend, which puts unnecessary load on the server running the backend. This is especially noticeable when generating TFRecords with masks (eg for Mask R-CNN).
Instead, the backend should just send the dataset in a generic, internal format and the conversion then happens on the client side, which can be all defined in the options of the job templates.
This internal format will require read/write plugins for the UFDL extension of wai.annotations.

**Comment by csterling** [comment]
These plugins are implemented in [ufdl-annotations-plugin](https://github.com/waikato-ufdl/ufdl-annotations-plugin).
