### ISSUE TITLE
Django notifications

### ISSUE THREAD

**Issue by fracpete** [waikato-ufdl/ufdl-backend#92]
In order for the **loop** getting notified about jobs failing or finishing, some form of notification framework needs to be available:

* push notifications (like on Android)?
* publish/subscriber framework?

Each kicked off job would get a unique ID (basically its PK), which can be used to reference them in the notifications.

**Comment by csterling** [comment]
Support for notifications (in general) is implemented in:
- d6e4d84ece3effd5c70f7bf8bcedf865aa4458bc
- [ufdl-python-client](https://github.com/waikato-ufdl/ufdl-python-client/commit/1e314a4d24ec2e9fd57cc941a80eb4a84497ef35)
- [ufdl-json-messages](https://github.com/waikato-ufdl/ufdl-json-messages/commit/282a09ecf3eea8d35e0015202781e94ea9e23f8d)

Currently only print and email notifications are supported. Push notifications is now a back-burner issue until there is a client to interact with.

**Comment by fracpete** [comment]
notifications are now available in the frontend via Redis
